application/main/routes.py
from flask import Blueprint, render_template, flash, request, abort, redirect, url_for
from application.models import Post, SubscribedUser, Submission
from application.main.utils import send_confirmation_email, send_everyone_email, send_test_email
from flask_login import current_user, login_required
from application.database import db
from application.main.forms import SubscriptionEmailForm

main = Blueprint("main", __name__)

@main.route('/')
@main.route('/home')
def home():
	submissions = Submission.query.filter_by(draft=False).all()
	return render_template("home.html", submissions=submissions)

@main.route('/about')
def about():
    return render_template("about.html", title="About")

@main.route('/sponsor')
def sponsor():
    return render_template("sponsor.html", title="Sponsor")

@main.route('/handle_subscription', methods=["GET", "POST"])
def handle_subscription():
	email_address = request.form['email']

	#check if there are any emails within our database matching the email that the user entered
	subscribed_user = SubscribedUser.query.filter_by(email=email_address).first()
	if subscribed_user: 
		flash("You have already subscribed!")
	else: #new subscriber
		user = SubscribedUser(email=email_address)
		db.session.add(user)
		db.session.commit()
		send_confirmation_email(email=email_address)
	return redirect(url_for("main.home"))

@main.route("/send_subscribers_email", methods=["GET", "POST"])
def send_subscribers_email():
	if current_user.role != "Admin":
		abort(403)

	form = SubscriptionEmailForm()
	if form.validate_on_submit():
		all_users = SubscribedUser.query.all()

		subject = form.subject.data
		content = form.content.data

		if form.test.data: #if sending test email
			send_test_email(subject=subject, content=content)
		else: #if sending real email
			recipients = [user.email for user in all_users]
			send_everyone_email(subject=subject, content=content, recipients=recipients)
		return redirect(url_for("main.home"))
	return render_template("send_subscribers_email.html", form=form)

@main.route("/gallery")
def gallery():
	submissions = Submission.query.filter_by(draft=False).all()
	return render_template("gallery.html", submissions=submissions)

application/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from application.database import db
from application.models import Post, Workshop
from tzlocal import get_localzone

posts = Blueprint("posts", __name__)

@posts.route("/create_post")
@login_required
def create_post():
	if current_user.role != "Admin":
		abort(403)
	return render_template("create_post.html")

@posts.route("/create_workshop")
@login_required
def create_workshop():
	if current_user.role != "Admin":
		abort(403)
	return render_template("create_workshop.html")

@posts.route("/handle_create_post", methods=["GET", "POST"])
@login_required
def handle_create_post():
	if current_user.role != "Admin":
		abort(403)

	title = request.form["title"]
	content = request.form["content"]
	post = Post(title=title, content=content)

	db.session.add(post)
	db.session.commit()
	return redirect(url_for("main.home"))

@posts.route("/handle_create_workshop", methods=["GET", "POST"])
@login_required
def handle_create_workshop():
	if current_user.role != "Admin":
		abort(403)

	title = request.form["title"]
	content = request.form["content"]
	post = Workshop(title=title, content=content)

	db.session.add(post)
	db.session.commit()
	return redirect(url_for("main.home"))

application/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, abort
from flask_login import login_user, current_user, logout_user, login_required
from application import bcrypt
from application.database import db
from application.models import User, Post, Submission, Workshop
from application.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm, SubmissionForm)
from application.users.utils import send_reset_email
import os
import random

users = Blueprint("users", __name__)

@users.route('/register', methods=["GET", "POST"])
def register():
	if current_user.is_authenticated: #if the user is already logged in
		return redirect(url_for("main.home")) #redirect the user back to the home page

	form = RegistrationForm()
	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data.encode("utf-8")).decode("utf-8")
		user = User(username=form.username.data, email=form.email.data, first_name=form.first_name.data, last_name=form.last_name.data, age=form.age.data, password=hashed_password, role="Member") #pass in the UTF-8 hashed password, not the plain text nor binary
		db.session.add(user)
		db.session.commit()

		flash(f"Account created for {form.username.data}!", "success") #bootstrap class category: success, danger, etc
		return redirect(url_for("users.login"))
	return render_template("register.html", title="Register", form=form)

@users.route('/login', methods=["GET", "POST"])
def login():
	if current_user.is_authenticated: #if the user is already logged in
		return redirect(url_for("main.home")) #redirect the user back to the home page
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first() #check if there are any emails within our database matching the email that the user entered
		if user and bcrypt.check_password_hash(user.password, form.password.data): #if the email exists and the password hash is valid
			login_user(user, remember=form.remember.data)

			#If the user tried to access a log-in only page and was redirected to /login, then automaticall send the user back to where they were going.
			next_page = request.args.get("next") #args is a dictionary but use args.get() not args[] because [] will throw an error if the key does not exist
			return redirect(next_page) if next_page else redirect(url_for("main.home"))
		else: #login is unsuccessful
			flash("Invalid!", "danger") #danger alert (Bootstrap)
	return render_template("login.html", title="Login", form=form)

@users.route("/logout")
def logout():
	logout_user()
	return redirect(url_for("main.home"))

@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
	form = UpdateAccountForm()
	if form.validate_on_submit():
		if form.picture.data:
			picture_filename = save_picture(form.picture.data)
			current_user.image_file = picture_filename
		current_user.username = form.username.data
		current_user.email = form.email.data
		current_user.bio = form.bio.data if form.bio.data else ""
		current_user.gender = form.gender.data if form.gender.data else ""
		db.session.commit()
		flash("Your account has been updated", "success")
		return redirect(url_for("users.account"))
	elif request.method == "GET": #populate the form fields with the user's existing data
		form.username.data = current_user.username
		form.email.data = current_user.email
		form.bio.data = current_user.bio
		form.gender.data = current_user.gender
	return render_template("account.html", title="Account", form=form)

@users.route("/reset_request", methods=["GET", "POST"])
def reset_request():
	if current_user.is_authenticated:
		return redirect(url_for("main.home"))	
	form = RequestResetForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		if send_reset_email(user):
			flash("An email has been sent with instructions to reset your password.", "info")
		else:
			flash("An error occured. Please try again later.", "danger")
		return redirect(url_for("users.login"))

	return render_template("reset_request.html", title="Request Password Reset", form=form)

@users.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_token(token):
	if current_user.is_authenticated:
		return redirect(url_for("main.home"))

	user = User.verify_reset_token(token)
	if not user:
		flash("The token is invalid or expired. Please request again.", "warning")
		return redirect(url_for("users.reset_request"))

	form = ResetPasswordForm()

	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
		user.password = hashed_password
		db.session.commit()
		flash(f"Your password has been updated!", "success")
		return redirect(url_for("users.login"))
	return render_template("reset_password.html", title="Reset Password", form=form)

@users.route("/portal/<username>", methods=["GET", "POST"])
@login_required
def portal(username):
	if current_user.username != username:
		abort(403)

	page = request.args.get("page", 1, type=int) #site will throw ValueError if anything other than integer passed as page number. Default page of 1.
	posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=4) #4 posts per page in descending order of date
	workshops = Workshop.query.all()

	user = User.query.filter_by(username=username).first()
	team_submissions = [submission for submission in user.submission]

	return render_template("portal.html", posts=posts, user=current_user, team_submissions=team_submissions, workshops=workshops)


@users.route('/handle_code', methods=["GET", "POST"])
def handle_code():
	user = User.query.filter_by(username=current_user.username).first() #get the current user
	if user.submission: # user is already in a team
		flash("You are already in a team!", "warning")
	elif request.form["submit_button"] == "Join": # join an existing team
		team_code = request.form['code_input']
		team_submission = Submission.query.filter_by(code=int(team_code)).first()

		if team_submission is None:
			flash("This team does not exist yet. Create a team instead?", "warning")
		elif len(team_submission.team_member) >= 4:
			flash("This team is full! Create a new one?", "warning")
		else:
			team_submission.team_member.append(user)

			db.session.commit()
			flash(f"You have been added to the team {team_submission.team_name}!", "success")
	elif request.form["submit_button"] == "Create": # create a new team
		existing_codes = [submission.code for submission in Submission.query.all()] #list of all existing codes
		new_code = random.choice([x for x in range(100000, 1000000) if x not in existing_codes]) #generate a new 6 digit code

		new_team = Submission(code=new_code, team_name=f"{user.username}'s project")
		new_team.team_member.append(user) #add this user to the new team

		db.session.add(new_team)
		db.session.commit()

		flash(f"You have created a new team! Share this code {new_code} with your friends now!", "success")
	else:
		flash(f"An unknown error occured. Please try again later.", "danger")
	return redirect(url_for("users.portal", username=current_user.username))


@users.route("/submission/<team_code>", methods=["GET", "POST"])
@login_required
def submission(team_code):
	team_submission = Submission.query.filter_by(code=team_code).first()

	if not team_submission: # this team does not exist
		abort(404) #page not found error

	valid_usernames = [member.username for member in team_submission.team_member]

	if current_user.username not in valid_usernames: #team exists, but no permission
		abort(403) #permission denied error

	form = SubmissionForm()

	if form.validate_on_submit():
		team_submission.github = form.github.data
		team_submission.video = form.video.data
		team_submission.team_name = form.team_name.data
		team_submission.school_name = form.school_name.data
		team_submission.description = form.description.data
		team_submission.draft = form.draft.data

		db.session.commit()
		return redirect(url_for("users.portal", username=current_user.username))
	elif request.method == "GET":
		form.github.data = team_submission.github
		form.video.data = team_submission.video
		form.school_name.data = team_submission.school_name
		form.team_name.data = team_submission.team_name
		form.description.data = team_submission.description
		form.draft.data = team_submission.draft
	return render_template("submission.html", form=form, user=current_user)

application/templates/about.html
{% extends "base.html" %} {% block content %}
    <header class="masthead" style="background-image:url('assets/img/about-bg.jpg');">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-10 col-lg-8 mx-auto">
                    <div class="site-heading">
                        <h1>About Us</h1><span class="subheading">This is what I do</span></div>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-lg-8 mx-auto">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
            </div>
        </div>
    </div>
    <hr>
    <footer>
        <div class="container">
            <div class="row"></div>
        </div>
    </footer>
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="assets/js/clean-blog.js"></script>
</body>

</html>
{% endblock content %}

application/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
    />
    <title>JHack</title>
    <script data-ad-client="ca-pub-4586330522755206" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
    />
    <link rel="stylesheet" href="../static/css/style.css">
    <!-- Google Fonts -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
    />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.2.0/p5.min.js"></script>
    <script src="https://cdn.ckeditor.com/4.16.0/standard/ckeditor.js"></script>
    <link rel="stylesheet" href="../static/fonts/font-awesome.min.css" />
    <link rel="stylesheet" href="../static/fonts/simple-line-icons.min.css" />
    <link rel="stylesheet" href="../static/css/bootstrap.min.css" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"
    />
    <link href="https://cdn.jsdelivr.net/npm/froala-editor@latest/css/froala_editor.pkgd.min.css" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-9ELYZEMQKW"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'G-9ELYZEMQKW');
    </script>
    <script src="/static/js/moment.min.js"></script>
  </head>

  <body>
    <nav
      class="navbar navbar-default navbar-expand-lg navbar-dark fixed-top"
      style="
        background-color: transparent !important;
        border-color: transparent;
        -webkit-transition: background-color 1s; /* Safari */
        transition: background-color 1s;
      "
      id="navb"
    >
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link item white-text" href="{{url_for('users.logout')}}"
                >Logout</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link item white-text" href="{{url_for('users.portal', username=current_user.username)}}"
                >Portal</a
              >
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link item white-text" href="{{url_for('users.register')}}">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link item white-text"href="{{url_for('users.login')}}">Log In</a>
            </li>

          {% endif %}

          <li class="nav-item">
            <a
              class="nav-link item white-text"
              
              href="{{url_for('main.home')}}"
              ><strong>Home</strong></a
            >
          </li>
          <li class="nav-item">
            <a
              class="nav-link item white-text"
              href="{{url_for('main.sponsor')}}"
              ><strong>Sponsor</strong></a
            >
          </li>
        </ul>
      </div>
    </nav>
    <div id="portal_h"></div>
      {% block content %}{% endblock %}
    <footer class="text-center text-white" style="background-color: #f1f1f1;">
      <!-- Grid container -->
      <div class="container pt-4">
        <!-- Section: Social media -->
        <section class="mb-4">

          <!-- Google Mail -->
          <a
            class="btn btn-link btn-floating btn-lg text-dark m-1"
            href="mailto: jhack@nagoyais.net"
            role="button"
            data-mdb-ripple-color="dark"
            ><i class="fas fa-envelope"></i>
          </a>

          <!-- Instagram -->
          <a
            class="btn btn-link btn-floating btn-lg text-dark m-1"
            href="https://github.com/orgs/404-Undefined/"
            role="button"
            data-mdb-ripple-color="dark"
            ><i class="fab fa-github"></i
          ></a>

        </section>
        <!-- Section: Social media -->
      </div>
      <!-- Grid container -->

      <!-- Copyright -->
      <div
        class="text-center text-dark p-3"
        style="background-color: rgba(0, 0, 0, 0.2)"
      >
        © 2020 Copyright:
        <a class="text-dark" href="">JHack.tech</a>
      </div>
      <!-- Copyright -->
    </footer>
  </body>
  <script
    src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"
  ></script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/froala-editor@latest/js/froala_editor.pkgd.min.js"></script>
  <script type="text/javascript" src="../static/js/main.js"></script>
  <!-- change to flask directory -->
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"
  ></script>
  {% block javascript %} {% endblock %}
</html>

application/templates/create_post.html
{% extends "base.html" %} {% block content %}
<header
  class="text-center text-white masthead"
  style="background-color: black; height: 30vh"
>
  <!--   style="
    background: url('https://images.unsplash.com/photo-1483401757487-2ced3fa77952?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1952&q=80') no-repeat center
      center;
    background-size: cover;
    height: 50vh;
  " -->
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-8 mx-auto">
        <h1 class="title">Create Announcement</h1>
      </div>
    </div>
  </div>
</header>
<form
  action="{{ url_for('posts.handle_create_post') }}"
  method="post"
  style="margin: 40px"
>
  <input name="title" placeholder="Title" style="margin-bottom: 20px" />
  <!-- <textarea name="content" placeholder="Content"></textarea> -->
  <textarea name="content" id="editor1" rows="10" cols="80"></textarea>
  <button type="submit" class="btn btn-primary btn-lg" style="margin-top: 20px">
    Post
  </button>
</form>
{% endblock content %}
<!-- the name of the block "content" in endblock is optonal -->

application/templates/create_workshop.html
{% extends "base.html" %} 

{% block content %}
<header class="text-center text-white masthead" style="background-color: black; height: 30vh">
  <div class="overlay"> </div>
  <div class="container">
    <div class="row">
      <div class="col-md-8 mx-auto">
        <h1 class="title">Create Workshop</h1>
      </div>
    </div>
  </div>
</header>
<form action="{{ url_for('posts.handle_create_workshop') }}" method="post" style="margin: 40px">
  <input name="title" placeholder="Title" style="margin-bottom: 20px" />
  <textarea name="content" id="editor3" rows="10" cols="80"></textarea>
  <button type="submit" class="btn btn-primary btn-lg" style="margin-top: 20px">
    Create
  </button>
</form>
{% endblock content %}

application/templates/portal.html
{% extends "base.html" %}
{% block content %}
<header class="text-center text-white masthead" style="background-color: black; height: 50vh" >
  <div class="overlay" id="portal_header" style="pointer-events:none;"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-8 mx-auto">
        <h1 class="title">{{user.username}}'s Portal</h1>
        <br>
      </div>
    </div>
    <!-- <p class="portal_text">Lorenz Attractor - a model of butterfly effect</p> -->
  </div>
</header>
    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %}
    <div class="alert alert-primary alert-dismissible fade show" id="flash" role="alert">
      <span>{{ message }}</span>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %} {% endif %} {% endwith %}
<section class="showcase">
  <div class="container-fluid p-0">
    <div class="row no-gutters">
      <div class="col-lg-6 order-lg-2 showcase-img" style="padding: 50px">
        <section>
          <form action="" method="post">
              {% for team_submission in team_submissions %}
              <div class="row no-gutters" style="border: 2px solid black; padding: 10px; margin-bottom:20px;">
                <div class="col-lg-6 d-flex justify-content-center pr-1" style="margin:auto;">
                  {{team_submission.team_name}}
                  <br>
                  Code - {{team_submission.code}}
                </div>
                <div class="col-lg-6 d-flex justify-content-center pr-1" style="padding: 10px; magin: auto;">
                  {% if team_submission.draft %}
                    <button class="btn btn-danger btn-sm" style="font-size: 20px; padding: 10px; magin: auto;">
                        <a href="{{url_for('users.submission', team_code=team_submission.code)}}" class="submission-button">Submit Project</a>
                    </button>
                  {% else %}
                    <p>Submitted</p>
                  {% endif %}
                </div> 
              </div>
              <hr class="break-line">
              {% endfor %}
          </form>
        </section>
        <section>
          <h2 style="text-align: center;">Team</h2>
          <form action="{{ url_for('users.handle_code') }}" method="post" style="">
            <div style="padding: 30px">
                <input
                  class="form-control form-control-lg"
                  type="number"
                  name="code_input"
                  placeholder="Enter your team code"
                  style="width: 50%;  width: 50%; display: block; margin: 0 auto 20px;"
                />
                <input class="btn btn-primary btn-block btn-lg" style="width: 50%; display: block; margin: 0 auto 10px; " name="submit_button" value="Join" type="submit"/>
                <div style="text-align: center; margin-bottom: 10px;  width: 100%; text-align: center; border-bottom: 1px solid #000; line-height: 0.1em; margin: 20px 0 20px;">
                  <span style="background:#fff;padding:0 10px;">OR</span>
                </div>
                <input name="submit_button" value="Create" class="btn btn-primary btn-block btn-lg" style="width: 50%; display: block; margin: 0 auto;" type="submit"/>
            </div>
          </form>
        </section>
        
        <hr class="break-line">

        <section>
          <h2 style="text-align: center;">Announcements</h2>
          <!-- Loop Announcement -->
          {% for post in posts.items %}
            <div style="border: 3px solid black; border-style: none none none solid; padding: 10px; margin-top: 10px; margin-bottom: 20px; background-color: #e8fcfc">
              <h3>{{post.title}}</h3>
              <p style="font-weight: bold;">{{ momentjs(post.date_posted).format("LLLL") }}<p>
              {{post.content|safe}}
            </div>
          {% endfor %}

          <!-- pagination buttons -->
          <div style="text-align: center;">
            {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=1) %}
              {% if page_num %}
                {% if posts.page == page_num %}
                  <a class="btn btn-primary mb-4" href="{{url_for('users.portal', username=user.username, page=page_num)}}">{{page_num}}</a>
                {% else %}
                  <a class="btn btn-outline-primary mb-4" href="{{url_for('users.portal', username=user.username, page=page_num)}}">{{page_num}}</a>
                {% endif %}
              {% else %}
                ...
              {% endif %}
            {% endfor %}
          </div>
        </section>

        <hr class="break-line">

        <section>
          <h2 style="text-align: center;">Resources</h2>
          <div class="speaker-container">
            Coding
            <ul>
              <li><a target="_blank" href="https://www.geeksforgeeks.org">Geek for Geek</a></li>
              <li><a target="_blank" href="https://education.github.com/pack">Github Student Development Pack</a></li>
              <li><a target="_blank" href="https://stackoverflow.com">Stack Overflow</a></li>
              <li><a target="_blank" href="https://www.youtube.com/user/schafer5">Corey Schafer's YouTube Channel (for Python)</a></li>
              <li><a target="_blank" href="https://www.youtube.com/user/shiffman">The Coding Train (Nature of Code) YouTube Channel (for JS)</a></li>
            </ul>
          </div>
        </section>
      </div>
      
      <div class="col-lg-6 order-lg-1 showcase-img" style="padding: 50px">
        <section>
          <div class="guide-container">
            <h2 style="text-align: center;">Submission Guide</h2>
            <p>Follow the guide below:</p>
            <iframe class="doc-embed" src="https://docs.google.com/document/d/e/2PACX-1vRYfMd0DSRPgJuIP19-HFPGgnfLUhaxClyg2syN-x9J2Ccm7svOHvPDr5Q8Ww2ghw6PhVG1apeMDcV7/pub?embedded=true"></iframe>
          </div>
        </section>

        <hr class="break-line">

        <section>
          <h2 style="text-align: center;">Workshops</h2>
          {% for workshop in workshops %}
            <div class="speaker-container">
              <div class="speaker-title">{{workshop.title}}</div>
              {{workshop.content|safe}}
            </div>
            <hr class="break-line">
          {% endfor %}
        </section>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

application/templates/reset_password.html
{% extends "base.html" %}
{% from "macro_field.html" import macro_field with context %}

{% block content %}
{% with messages = get_flashed_messages(with_categories=true) %} {% if
messages %} {% for category, message in messages %}
<div class="alert alert-primary alert-dismissible fade show" id="flash" role="alert">
	<span>{{ message }}</span>
	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
	<span aria-hidden="true">&times;</span>
	</button>
</div>
{% endfor %} {% endif %} {% endwith %}


<div class="row mx-auto" style="height: 100vh">
  <div
    class="col-lg-6 text-white order-lg-2 showcase-img d-none d-lg-block"
    style="
      background: url('https://jhack-hackathon.s3-ap-northeast-1.amazonaws.com/static/assets/images/login.jpg')
        no-repeat;
      background-size: cover;
    "
  >
    <span></span>
  </div>

  <div class="col-lg-6 my-auto mx-auto order-lg-1 showcase-text mb-3 lead">
	<form method="POST" action="">
		{{ form.hidden_tag() }} <!-- Adds a CSRF (Cross Site Request Forgery) token -->
		<fieldset class="form-group">
			<legend class="border-bottom mb-4"> Reset Password </legend>
			{{ macro_field(form.password) }}
			{{ macro_field(form.confirm_password) }}
		</fieldset>

		<div class="form-group">
			{{ form.submit(class="btn btn-outline-info") }}
		</div>
	</form>
  </div>
</div>
{% endblock content %}